/* M8 verifier workbench: queue -> summary -> evidence -> decision. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let latest=null,selected=null,centralCases=[],logEntries=[];
  const stage={needs_review:'Needs review',awaiting_screening:'Awaiting screening evidence',awaiting_diagnostic_result:'Awaiting diagnostic result',diagnostic_review:'Diagnostic review',diagnosed:'Diagnosed',treatment_follow_up:'Treatment follow-up',closed:'Closed'};
  function log(m){logEntries.unshift('['+new Date().toLocaleTimeString()+'] '+m);$('log').textContent=logEntries.slice(0,25).join('\n');}
  async function api(path,opts={}){let r;try{r=await fetch(path,opts);}catch(_){throw Error('Local device process unavailable');}let b;try{b=await r.json();}catch(_){throw Error('Invalid JSON response');}if(!r.ok)throw Error(b.detail||b.error||'Request failed');return b;}
  const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
  function card(item){const sel=item.case_id===selected?' selected':'';return `<div class="case-card${sel}" data-id="${esc(item.case_id)}"><div class="case-top"><span class="case-id">${esc(item.case_id.slice(0,8))} · r${item.revision}</span><span class="status-chip">${esc(item.case_status)}</span></div><div class="case-meta">${esc(item.location)} · ${esc(stage[item.current_stage]||item.current_stage)}</div>${item.current_stage==='needs_review'?'<div class="case-extra case-alert">Action required: reviewer decision</div>':''}</div>`;}
  function input(name,label,type='text',value='',extra=''){return `<label>${esc(label)}<br><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${extra}></label>`;}
  function select(name,label,opts){return `<label>${esc(label)}<br><select name="${esc(name)}">${opts.map(o=>`<option value="${esc(o[0])}">${esc(o[1])}</option>`).join('')}</select></label>`;}
  const check=(name,label)=>`<label><input type="checkbox" name="${esc(name)}"> ${esc(label)}</label>`;
  function actions(c){const a=c.asha_assignment,d=c.diagnosis,s=c.case_status,choices=[];if(['ready_for_review','pending_additional_test'].includes(s))choices.push(['review',s==='pending_additional_test'?'Direct diagnostic referral':'Review decision']);if(s==='pending_additional_test')choices.push(['screen_route','Allocate screening site']);if(['routed_for_diagnostics'].includes(s)){choices.push(['diagnostic_order','Order diagnostic test']);if(c.diagnostic_tests.some(x=>x.result==='pending'))choices.push(['diagnostic_result','Record lab result']);}if(s==='diagnostic_result_available')choices.push(['diagnosis','Record clinician diagnosis']);if(s==='diagnosed'&&d){if(!d.treatment_plan_confirmed)choices.push(['confirm_plan','Confirm treatment plan']);else if(!d.treatment_started_at)choices.push(['start_treatment','Record treatment start']);else if(!a.asha_id)choices.push(['treatment_support','Assign ASHA treatment support']);}if(a.asha_id){choices.push(['followup','Record follow-up']);if(a.support_phase==='treatment_support'){choices.push(['pickup_schedule','Schedule pickup']);if(a.medicine_pickup_log.some(x=>x.status==='scheduled'))choices.push(['pickup_result','Record pickup outcome']);}}return choices;}
  function fields(action,c){
    if(action==='review')return select('decision','Decision',[...(c.case_status==='pending_additional_test'?[['intervention_required','Refer for diagnostic testing now']]:[['more_tests_needed','Request more screening evidence'],['intervention_required','Refer for diagnostic testing'],['not_required','No diagnostic referral']])])+`<div class="check-grid">${check('xray','Request X-ray')}${check('esr','Request ESR')}</div>`+select('site_id','Selected synthetic site',[['','No site selected'],['DEMO-LAB-01','DEMO-LAB-01'],['DEMO-LAB-02','DEMO-LAB-02'],['DEMO-SCREEN-01','DEMO-SCREEN-01'],['DEMO-SCREEN-02','DEMO-SCREEN-02']])+input('notes','Reviewer rationale','text','');
    if(action==='screen_route')return select('site_id','Synthetic screening site',[['DEMO-SCREEN-01','DEMO-SCREEN-01'],['DEMO-SCREEN-02','DEMO-SCREEN-02']]);
    if(action==='diagnostic_order')return select('test_type','Diagnostic test',['xpert_mtb_rif','xpert_ultra','truenat','culture','smear_microscopy','other_who_recommended_rapid_test'].map(x=>[x,x]))+input('specimen_ref','Synthetic specimen ID','text','DEMO-SPEC-001')+check('specimen_collected','Specimen collected now');
    if(action==='diagnostic_result')return select('test_id','Pending test',c.diagnostic_tests.filter(x=>x.result==='pending').map(x=>[x.test_id,x.test_type]))+select('result','Lab result',[['positive','positive'],['negative','negative'],['indeterminate','indeterminate']]);
    if(action==='diagnosis')return select('classification','Classification',[['bacteriologically_confirmed','Bacteriologically confirmed'],['clinically_diagnosed','Clinically diagnosed']])+select('supporting_test_id','Supporting completed test',[['','Select test'],...c.diagnostic_tests.filter(x=>x.result!=='pending').map(x=>[x.test_id,x.test_type+' · '+x.result])])+input('clinical_rationale','Clinical rationale')+check('full_course_treatment_decided','Full-course treatment decided')+check('treatment_plan_confirmed','Treatment plan confirmed');
    if(action==='confirm_plan'||action==='start_treatment')return '<p>Confirm this explicit clinician event.</p>';
    if(action==='navigation'||action==='treatment_support')return input('asha_id','Synthetic ASHA ID','text','demo-asha-01');
    if(action==='followup')return select('kind','Follow-up phase',[['navigation','navigation'],['treatment','treatment']])+input('summary','Factual follow-up summary')+select('trend','Trend',[['','Not classified'],['improving','improving'],['no_change','no change'],['concerning','concerning']]);
    if(action==='pickup_schedule')return input('scheduled_date','Pickup date','date');
    if(action==='pickup_result')return select('scheduled_date','Scheduled pickup',c.asha_assignment.medicine_pickup_log.filter(x=>x.status==='scheduled').map(x=>[x.scheduled_date,x.scheduled_date]))+select('status','Outcome',[['picked_up','Picked up'],['missed','Missed']])+input('reschedule_date','Replacement date if missed','date');
    return '';
  }
  function renderWorkbench(){if(!latest){$('caseWorkbench').innerHTML='<p>Select a synced case to inspect it.</p>';return;}const c=latest.case,v=latest.view,request=c.review_history.length?c.review_history[c.review_history.length-1]:null;const pending=request?.requested_tests?.filter(t=>!c[t].available)||[];const acts=actions(c);$('caseWorkbench').innerHTML=`<div class="case-detail"><div class="detail-header"><div><div class="detail-kicker">CASE</div><h3>${esc(c.case_id)}</h3><div class="detail-muted">Revision ${c.revision} · ${esc(c.case_status)} · ${esc(stage[v.current_stage]||v.current_stage)}</div></div><span class="stage-badge">${esc(stage[v.current_stage]||v.current_stage)}</span></div><section class="detail-section"><h4>1. Summary</h4><div class="summary-box">${esc(c.case_summary.brief_text)}</div></section><section class="detail-section"><h4>2. Evidence</h4><div class="detail-grid"><div><strong>X-ray</strong><br>${c.xray.available?esc(c.xray.model_flag||'Captured, not model-processed'):'Not available'}${c.xray.image_ref?'<br><span class="detail-muted">'+esc(c.xray.image_ref)+'</span>':''}</div><div><strong>ESR</strong><br>${c.esr.available?esc(c.esr.value)+' mm/hr · '+esc(c.esr.flag):'Not available'}${c.esr.reference_range_used?'<br><span class="detail-muted">'+esc(c.esr.reference_range_used)+'</span>':''}</div></div>${pending.length?`<div class="detail-alert severity-action"><strong>Worker response needed:</strong> ${esc(pending.join(' + '))}</div>`:''}</section><section class="detail-section"><h4>3. Decision</h4>${acts.length?`<form id="caseActionForm">${select('action','Next explicit event',acts)}<div id="actionFields"></div><button type="submit">Record decision / event</button></form>`:'<p class="detail-muted">No decision is currently available.</p>'}<pre id="actionFeedback"></pre></section><details class="detail-section"><summary>Other case information</summary><p><strong>Patient:</strong> ${esc(v.patient.patient_ref)} · age ${v.patient.age} · ${esc(v.patient.sex)} · ${esc(v.patient.location)}</p><p><strong>Diagnosis:</strong> ${esc(c.diagnosis?.classification||'Not established')}</p><p><strong>ASHA:</strong> ${esc(c.asha_assignment.support_phase||'Not assigned')}</p><p><strong>Alerts:</strong> ${esc(v.alerts.map(a=>a.label).join(' | ')||'None')}</p><p><strong>History:</strong> ${v.history_count} events</p></details><div class="detail-tools"><button id="jsonBtn" type="button" class="secondary">Inspect canonical JSON</button> <button id="projectionBtn" type="button" class="secondary">Inspect read model</button></div><small>DEMO ONLY. No real patient information. Screening evidence does not establish TB diagnosis.</small></div>`;$('jsonBtn').onclick=()=>showJson(c);$('projectionBtn').onclick=()=>showJson(v);if(acts.length){const f=$('caseActionForm'),choose=f.elements.action,paint=()=>{$('actionFields').innerHTML=fields(choose.value,c);};choose.onchange=paint;paint();f.onsubmit=submitAction;}}
  function showJson(obj){$('modalJson').textContent=JSON.stringify(obj,null,2);$('modalBackdrop').classList.add('open');}
  async function selectCase(id){try{latest=await api('/v1/dashboard/cases/'+encodeURIComponent(id));selected=id;renderWorkbench();document.querySelectorAll('.case-card').forEach(e=>e.classList.toggle('selected',e.dataset.id===id));log('Loaded '+id.slice(0,8)+' at revision '+latest.case.revision);}catch(e){log('Could not load case: '+e.message);}}
  async function submitAction(event){event.preventDefault();if(!latest)return;const form=$('caseActionForm'),values=Object.fromEntries(new FormData(form)),action=values.action,payload={...values,expected_revision:latest.case.revision,requested_tests:action==='review'?['xray','esr'].filter(k=>Boolean(values[k])):[]};if(action==='review'){delete payload.xray;delete payload.esr;}if(action==='diagnostic_order')payload.specimen_collected=Boolean(values.specimen_collected);if(action==='diagnostic_result'){}if(action==='diagnosis'){payload.supporting_test_ids=values.supporting_test_id?[values.supporting_test_id]:[];payload.full_course_treatment_decided=Boolean(values.full_course_treatment_decided);payload.treatment_plan_confirmed=Boolean(values.treatment_plan_confirmed);delete payload.supporting_test_id;}$('actionFeedback').textContent='Submitting…';try{const r=await post('/v1/dashboard/cases/'+encodeURIComponent(selected)+'/actions',payload);latest={case:r.case,view:r.view};renderWorkbench();log('Recorded '+action+' on '+selected.slice(0,8)+' revision '+latest.case.revision);await refresh();}catch(e){$('actionFeedback').textContent='NOT RECORDED: '+e.message;}}
  async function refresh(){try{const local=await api('/v1/outbox');$('localQueue').innerHTML=local.outbox.length?local.outbox.map(x=>`<div class="case-card" data-id="${esc(x.case_id)}"><div class="case-top"><span class="case-id">${esc(x.case_id.slice(0,8))} · r${x.revision}</span><span class="status-chip">${esc(x.sync_status)}</span></div><div class="case-meta">${x.attempt_count} transfer attempt(s)</div></div>`).join(''):'<div class="empty">No locally stored cases.</div>';}catch(e){$('localQueue').textContent=e.message;}try{await api('/v1/dashboard/health');$('connDot').classList.add('online');$('connLabel').textContent='Central reachable';const d=await api('/v1/dashboard/cases');centralCases=d.cases;$('centralQueue').innerHTML=centralCases.length?centralCases.map(card).join(''):'<div class="empty">No cases have synced to central SQLite yet.</div>';}catch(e){$('connDot').classList.remove('online');$('connLabel').textContent='Central unavailable';$('centralQueue').innerHTML='<div class="empty">Central receiver unavailable. Local cases remain in SQLite.</div>';centralCases=[];}}
  $('newCaseBtn').textContent='+ Open field intake';$('newCaseBtn').onclick=()=>location.href='/field';$('connBtn').textContent='Retry sync';$('connBtn').onclick=async()=>{ $('connBtn').disabled=true;try{await post('/v1/sync',{});}catch(e){log(e.message);}finally{$('connBtn').disabled=false;await refresh();}};$('centralQueue').addEventListener('click',e=>{const t=e.target.closest('.case-card');if(t)selectCase(t.dataset.id);});$('modalClose').onclick=()=>$('modalBackdrop').classList.remove('open');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.remove('open');};log('M8 focused workbench: queue → summary → evidence → decision.');refresh();
})();
