/* M8 field intake. Typed and speech text share one server summary pipeline. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const STEPS=['intro','age','sex','area','cough','duration','fever','sweats','weightloss','narrative','tests','consent','review','done'];
  const words={en:{yes:'Yes',no:'No',unknown:"Don't know",required:'Choose an answer to continue.',age:'Enter a whole age between 18 and 120.',duration:'Enter whole cough days (1 or more), or leave blank if unknown.',consent:'Both consents must be checked before saving.',review:'Check the draft before saving.',voiceConsent:'Check speech-processing consent before using the microphone.',noSpeech:'Speech recognition is unavailable here. Type instead.',saved:'Saved on this device. ',synced:'Central receiver acknowledged the case.',queued:'Central unavailable; case remains in local SQLite. You can retry later.',error:'Not saved: ',voice:'Listening… speak clearly.',stopped:'Review the transcript and correct it before saving.',type:'Typing is enabled. You can edit the text at any time.',voiceErr:'Speech could not be transcribed. Type instead.',summaryWait:'Waiting for text…',summaryFail:'Summary is temporarily unavailable; the text will still be saved.'},hi:{yes:'हाँ',no:'नहीं',unknown:'पता नहीं',required:'आगे बढ़ने के लिए उत्तर चुनें।',age:'पूरे वर्ष में 18 से 120 तक आयु भरें।',duration:'खाँसी के दिनों की पूर्ण संख्या भरें, या पता न हो तो खाली छोड़ें।',consent:'सहेजने से पहले दोनों सहमति बॉक्स चुनें।',review:'सहेजने से पहले मसौदा जाँचें।',voiceConsent:'माइक्रोफोन उपयोग से पहले सहमति बॉक्स चुनें।',noSpeech:'इस ब्राउज़र में आवाज़ पहचान उपलब्ध नहीं। कृपया लिखें।',saved:'डिवाइस पर सहेजा गया। ',synced:'केंद्रीय सेवा ने केस स्वीकार कर लिया है।',queued:'केंद्रीय सेवा उपलब्ध नहीं; केस स्थानीय SQLite में सुरक्षित है। बाद में फिर प्रयास करें।',error:'सहेजा नहीं गया: ',voice:'सुन रहा है… साफ़ बोलें।',stopped:'पाठ जाँचें और गलत शब्द सुधारें।',type:'लिखना चालू है। आप पाठ कभी भी बदल सकते हैं।',voiceErr:'आवाज़ लिखी नहीं जा सकी। कृपया लिखें।',summaryWait:'पाठ की प्रतीक्षा है…',summaryFail:'सारांश अभी उपलब्ध नहीं है; पाठ फिर भी सुरक्षित रहेगा।'}};
  let step=0,source='text',savedAt=null,caseId=null,listening=null,stopRequested=false,busy=false,summaryTimer=null,voiceRestartTimer=null;
  const lang=()=>document.querySelector('input[name=language]:checked')?.value||'en';
  const t=k=>words[lang()][k];
  const val=name=>document.querySelector(`input[name="${name}"]:checked`)?.value;
  const tri=name=>({yes:true,no:false,unknown:null})[val(name)];
  const printable=v=>v===true?t('yes'):v===false?t('no'):t('unknown');
  function translate(){document.documentElement.lang=lang();document.querySelectorAll('[data-en][data-hi]').forEach(el=>{el.textContent=el.dataset[lang()];});for(const id of ['cough','fever','sweats','weightloss']){const box=$(id+'Choices'),current=val(id);box.replaceChildren();for(const option of ['yes','no','unknown']){const l=document.createElement('label'),i=document.createElement('input'),s=document.createElement('span');i.type='radio';i.name=id;i.value=option;i.checked=option===current;s.textContent=t(option);l.append(i,s);box.append(l);}}}
  function visibleSteps(){return STEPS.filter(s=>s!=='duration'||val('cough')==='yes');}
  function show(){const current=STEPS[step];document.querySelectorAll('.step').forEach(s=>s.hidden=s.id!==`step-${current}`);const steps=visibleSteps(),order=steps.indexOf(current);$('bar').max=steps.length-1;$('bar').value=Math.max(1,order+1);$('progress').textContent=`${Math.max(1,order+1)} / ${steps.length-1}`;$('back').hidden=step===0||current==='done';$('next').hidden=current==='done';$('next').textContent=current==='review'?(lang()==='hi'?'केस सहेजें':'Save case'):lang()==='hi'?'आगे':'Next';if(current==='review')$('preview').textContent=preview();}
  function preview(){const cough=tri('cough'),duration=$('duration').value.trim();return [`Age / आयु: ${$('age').value}`,`Sex / लिंग: ${val('sex')}`,`Area / क्षेत्र: ${$('area').selectedOptions[0].textContent}`,`Cough / खाँसी: ${printable(cough)}${cough===true?` (${duration||t('unknown')} ${lang()==='hi'?'दिन':'days'})`:''}`,`Fever / बुखार: ${printable(tri('fever'))}`,`Night sweats / रात का पसीना: ${printable(tri('sweats'))}`,`Weight loss / वजन घटाना: ${printable(tri('weightloss'))}`,`X-ray report / एक्स-रे: ${$('xrayReport').value}`,`ESR report / ESR: ${$('esrReport').value}`,`X-ray upload: ${$('xrayFile').files[0]?.name||'none'}`,`ESR value: ${$('esrValue').value||'none'}`,$('narrative').value.trim()?`Narrative / विवरण: ${$('narrative').value.trim()}`:'',`Summary / सारांश: ${$('summaryText').textContent}`,'For qualified human review only; no TB diagnosis.'].filter(Boolean).join('\n');}
  function checkStep(){const current=STEPS[step];let e='';if(current==='age'&&(!/^(?:[1-9]\d*)$/.test($('age').value.trim())||+$('age').value<18||+$('age').value>120))e=t('age');else if(['cough','fever','sweats','weightloss'].includes(current)&&!val(current))e=t('required');else if(current==='duration'&&$('duration').value.trim()&&(!/^\d+$/.test($('duration').value.trim())||+$('duration').value<1||+$('duration').value>36500))e=t('duration');else if(current==='consent'&&(!$('consent').checked||!$('synthetic').checked))e=t('consent');else if(current==='review'&&!$('reviewed').checked)e=t('review');$('feedback').textContent=e;return !e;}
  function structured(){return{cough_present:tri('cough'),cough_duration_days:tri('cough')===true&&$('duration').value.trim()?Number($('duration').value):null,fever:tri('fever'),night_sweats:tri('sweats'),weight_loss:tri('weightloss')};}
  async function updateSummary(){const text=$('narrative').value.trim();$('liveTranscript').textContent=text;if(!text){$('summaryText').textContent=t('summaryWait');return;}try{const r=await fetch('/v1/intake/summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({raw_text:text,structured:structured()})});const body=await r.json();if(!r.ok)throw Error(body.detail||body.error);$('summaryText').textContent=body.summary+`\n\nMethod: ${body.method}. Not a diagnosis.`;}catch(_){$('summaryText').textContent=t('summaryFail');}}
  function scheduleSummary(){clearTimeout(summaryTimer);summaryTimer=setTimeout(updateSummary,250);}
  function collect(){const timestamp=savedAt||new Date().toISOString();savedAt=timestamp;caseId=caseId||(crypto.randomUUID?.()||null);if(!caseId)throw Error('Secure UUID generation unavailable (open localhost).');const cough=tri('cough');return{case_id:caseId,created_at:timestamp,consent_recorded_at:timestamp,consent_confirmed:$('consent').checked,synthetic_acknowledged:$('synthetic').checked,age:Number($('age').value),sex:val('sex'),location:$('area').value,cough_present:cough,cough_duration_days:cough===true&&$('duration').value.trim()?Number($('duration').value):null,fever:tri('fever'),night_sweats:tri('sweats'),weight_loss:tri('weightloss'),raw_text:$('narrative').value.trim()||null,text_source:source,audio_recording_consent:source==='voice'&&$('voiceConsent').checked,xray_available:false,esr_available:false,xray_report_claim:$('xrayReport').value,esr_report_claim:$('esrReport').value};}
  async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||d.error||String(r.status));return d;}
  function filePayload(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Could not read X-ray file'));reader.onload=()=>resolve({filename:file.name,mime_type:file.type,content_base64:String(reader.result).split(',')[1]});reader.readAsDataURL(file);});}
  async function attachEvidence(){const messages=[];let revision=null;try{const current=await fetch(`/v1/field/cases/${caseId}/requests`);if(current.ok){const body=await current.json();revision=body.revision;}}catch(_){}
    if($('xrayFile').files[0]){const file=$('xrayFile').files[0];$('xrayUploadStatus').textContent='Uploading X-ray…';try{const upload=await filePayload(file);const result=await post(`/v1/field/cases/${caseId}/evidence`,{evidence_type:'xray',expected_revision:revision,captured_at:new Date().toISOString(),upload});revision=result.case?.revision??revision;messages.push('X-ray evidence attached.');}catch(e){messages.push('X-ray not attached: '+e.message);}}
    if($('esrValue').value.trim()){try{const value=Number($('esrValue').value),upper=Number($('esrUpper').value);const reference=$('esrRef').value.trim();if(!reference)throw Error('Enter the lab report reference.');const result=await post(`/v1/field/cases/${caseId}/evidence`,{evidence_type:'esr',expected_revision:revision,captured_at:new Date().toISOString(),value,lab_upper_limit:upper,reference_source:reference});revision=result.case?.revision??revision;messages.push('ESR evidence attached.');}catch(e){messages.push('ESR not attached: '+e.message);}}return messages;}
  async function save(){if(busy)return;busy=true;$('next').disabled=true;try{const raw=collect(),result=await post('/v1/intake',raw);caseId=result.case.case_id;let messages=[t('saved')];try{const evidence=await attachEvidence();messages.push(...evidence);const outcome=await post('/v1/sync',{});const row=outcome.outbox.find(x=>x.case_id===raw.case_id&&x.revision===Math.max(...outcome.outbox.filter(y=>y.case_id===raw.case_id).map(y=>y.revision)));if(row?.sync_status==='acked')messages.push(t('synced'));else messages.push(t('queued'));}catch(e){messages.push(t('queued')+' '+e.message);} $('doneMessage').textContent=messages.join(' ');step=STEPS.indexOf('done');show();}catch(e){$('feedback').textContent=t('error')+e.message;}finally{busy=false;$('next').disabled=false;}}
  $('next').onclick=async()=>{if(!checkStep())return;if(STEPS[step]==='review'){await save();return;}const steps=visibleSteps(),i=steps.indexOf(STEPS[step]);step=STEPS.indexOf(steps[i+1]);show();};
  $('back').onclick=()=>{if(STEPS[step]==='review')$('reviewed').checked=false;const steps=visibleSteps(),i=steps.indexOf(STEPS[step]);if(i>0){step=STEPS.indexOf(steps[i-1]);show();}};
  document.querySelectorAll('input[name=language]').forEach(x=>x.addEventListener('change',()=>{translate();show();scheduleSummary();}));
  $('narrative').addEventListener('input',()=>{source='text';scheduleSummary();});
  $('typeInstead').onclick=()=>{stopSpeech();source='text';$('voiceStatus').textContent=t('type');$('narrative').focus();};
  $('voiceConsent').onchange=()=>{if(!$('voiceConsent').checked){stopSpeech();if(source==='voice'){$('narrative').value='';$('liveTranscript').textContent='';source='text';scheduleSummary();}}};
  function stopSpeech(){stopRequested=true;clearTimeout(voiceRestartTimer);voiceRestartTimer=null;if(listening){try{listening.stop();}catch(_){}}listening=null;$('speak').textContent=lang()==='hi'?'बोलना शुरू करें':'Start speaking';$('voiceStatus').textContent=t('stopped');}
  function startSpeech(){if(!('SpeechRecognition' in window||'webkitSpeechRecognition' in window)){ $('voiceStatus').textContent=t('noSpeech');return;}if(!$('voiceConsent').checked){$('voiceStatus').textContent=t('voiceConsent');return;}stopRequested=false;source='voice';clearTimeout(voiceRestartTimer);const R=window.SpeechRecognition||window.webkitSpeechRecognition;const rec=new R();rec.continuous=true;rec.interimResults=true;rec.lang=lang()==='hi'?'hi-IN':'en-IN';rec.maxAlternatives=1;listening=rec;$('speak').textContent=lang()==='hi'?'सुनना बंद करें':'Stop listening';$('voiceStatus').textContent=t('voice');let finalText='';rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+text;else interim+=text;}if(finalText){const current=$('narrative').value.trim();$('narrative').value=(current?current+' ':'')+finalText.trim();finalText='';}const committed=$('narrative').value.trim();$('liveTranscript').textContent=interim?`${committed}${committed?' ':''}${interim.trim()}`:committed;scheduleSummary();};rec.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){stopRequested=true;$('voiceStatus').textContent=t('voiceErr');}else if(e.error!=='aborted'){$('voiceStatus').textContent=t('voice');}};rec.onend=()=>{if(listening!==rec)return;listening=null;if(!stopRequested){$('voiceStatus').textContent=t('voice');voiceRestartTimer=setTimeout(()=>{if(!stopRequested)startSpeech();},250);}else{$('speak').textContent=lang()==='hi'?'बोलना शुरू करें':'Start speaking';}};try{rec.start();}catch(_){listening=null;$('voiceStatus').textContent=t('voiceErr');}}
  $('speak').onclick=()=>{if(listening)stopSpeech();else startSpeech()};
$('xrayFile').onchange=()=>{$('xrayUploadStatus').textContent=$('xrayFile').files[0]?`Selected: ${$('xrayFile').files[0].name}`:'';};
  translate();show();
})();
