/* M8 worker case tracker. Evidence is submitted against the existing case ID. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  let remote=new Map();
  const stage={ready_for_review:'Awaiting review / समीक्षा की प्रतीक्षा',pending_additional_test:'More tests requested / अतिरिक्त जाँच माँगी गई',routed_for_diagnostics:'Sent for diagnostic testing / निदान जाँच के लिए भेजा',diagnostic_result_available:'Result awaiting clinician / डॉक्टर की प्रतीक्षा',diagnosed:'Diagnosis recorded / निदान दर्ज',closed:'Closed by reviewer / समीक्षा पूरी'};
  async function api(url,body){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.detail||v.error||String(r.status));return v;}
  const line=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
  function filePayload(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Could not read X-ray file'));reader.onload=()=>resolve({filename:file.name,mime_type:file.type,content_base64:String(reader.result).split(',')[1]});reader.readAsDataURL(file);});}
  function evidenceForm(id,request){const wrap=document.createElement('div');wrap.className='request';wrap.append(line('strong','Action required / कार्रवाई आवश्यक'));wrap.append(line('p','Verifier requested: '+request.pending_tests.join(' + ')));if(request.summary) {const s=document.createElement('div');s.className='summary';s.textContent=request.summary;wrap.append(s);}const form=document.createElement('form');form.dataset.caseId=id;const grid=document.createElement('div');grid.className='grid';if(request.pending_tests.includes('xray')){const x=document.createElement('div');const l=document.createElement('label');l.textContent='Chest X-ray image / छाती का एक्स-रे';const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg';input.name='xray';l.append(input);x.append(l);grid.append(x);}if(request.pending_tests.includes('esr')){const x=document.createElement('div');x.innerHTML='<label>ESR value (mm/hr) / ESR मान<input name="value" type="number" min="0" max="500" step="0.1" required></label><label>Lab upper limit / लैब सीमा<input name="upper" type="number" min="0.1" max="250" step="0.1" placeholder="22" required></label><label>Lab report reference / लैब रिपोर्ट संदर्भ<input name="ref" type="text" placeholder="DEMO-LAB-REPORT-001" required></label>';grid.append(x);}form.append(grid);const submit=document.createElement('button');submit.type='submit';submit.textContent='Submit requested evidence / माँगा गया प्रमाण भेजें';form.append(submit);const status=document.createElement('p');status.className='status';form.append(status);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;status.textContent='Submitting…';try{if(request.pending_tests.includes('xray')){const f=form.elements.xray.files[0];if(!f)throw Error('Choose the X-ray image first.');const upload=await filePayload(f);const current=await api(`/v1/field/cases/${id}/requests`);const xrayResult=await api(`/v1/field/cases/${id}/evidence`,{evidence_type:'xray',expected_revision:current.revision,upload,captured_at:new Date().toISOString()});}if(request.pending_tests.includes('esr')){const value=Number(form.elements.value.value),upper=Number(form.elements.upper.value);const current=await api(`/v1/field/cases/${id}/requests`);const reference=form.elements.ref.value.trim();if(!reference)throw Error('Enter the lab report reference.');await api(`/v1/field/cases/${id}/evidence`,{evidence_type:'esr',expected_revision:current.revision,value,lab_upper_limit:upper,reference_source:reference,captured_at:new Date().toISOString()});}status.textContent='Evidence submitted for this case. / इस केस के लिए प्रमाण भेज दिया गया।';await refresh();}catch(err){status.textContent='Not submitted: '+err.message;submit.disabled=false;}};wrap.append(form);return wrap;}
  async function refresh(){try{const out=await api('/v1/outbox');remote=new Map();try{const central=await api('/v1/dashboard/cases');remote=new Map(central.cases.map(c=>[c.case_id,c]));}catch(_){}const cases=new Map();for(const row of out.outbox){const current=cases.get(row.case_id);if(!current||row.revision>current.revision)cases.set(row.case_id,row);}const box=$('cards');box.replaceChildren();if(!cases.size)box.append(line('p','No saved cases / अभी कोई केस नहीं'));for(const [id,row] of cases){const div=document.createElement('article');div.className='card';div.append(line('strong','Case / केस '+id.slice(0,8)));const remoteCase=remote.get(id);div.append(line('p',row.sync_status==='acked'?'Sent to central / केंद्र को भेजा गया':row.sync_status==='needs_attention'?'Needs attention / ध्यान आवश्यक':'Saved on device / डिवाइस पर सुरक्षित'));if(remoteCase){div.append(line('p',stage[remoteCase.case_status]||remoteCase.case_status));const screening=document.createElement('p');screening.textContent=`Screening: X-ray ${remoteCase.xray_available?'available':'not available'} · ESR ${remoteCase.esr_available?'available':'not available'}`;div.append(screening);}try{const req=await api(`/v1/field/cases/${id}/requests`);if(req.has_request)div.append(evidenceForm(id,req));else if(remoteCase)div.append(line('p',req.case_status==='ready_for_review'?'No additional evidence requested. / अतिरिक्त प्रमाण नहीं माँगा गया।':'No worker action is currently requested. / अभी कोई कार्य नहीं माँगा गया।'));}catch(_){}box.append(div);}$('notice').textContent=remote.size?'Central reachable / केंद्र उपलब्ध':'Central offline; locally saved cases remain here / केंद्र बंद है, केस यहाँ सुरक्षित हैं';}catch(e){$('notice').textContent='Local service unavailable / स्थानीय सेवा बंद है: '+e.message;}}
  $('retry').onclick=async()=>{$('retry').disabled=true;try{await api('/v1/sync',{});}catch(e){$('notice').textContent='Could not send yet; local cases remain saved: '+e.message;}finally{$('retry').disabled=false;await refresh();}};$('refresh').onclick=refresh;refresh();
})();
